added check if can't make the tmpdir(s)

diff --git a/stackjump b/stackjump
--- a/stackjump
+++ b/stackjump
@@ -42,6 +42,9 @@ TMPDIR="/tmp/$DATETIME"
 ISODIR="$TMPDIR/ISO"
 INITRD="$TMPDIR/initrd"
 mkdir -p $ISODIR $INITRD
+if [ $? != 0 ]; then
+  echo "Unable to create tmpdir $TMPDIR subdir(s)" && exit
+fi
 
 ## SANITY CHECKS ##
 
