add the chef repo integration.  you can specify your chef repo as an external dir, or a dir inside of your stackjump skeleton, or a external dir via github url, or a dir inside of your github stackjump skeleton.

diff --git a/stackjump b/stackjump
--- a/stackjump
+++ b/stackjump
@@ -7,10 +7,12 @@ USAGE="$0 options
   -p preseed (or use [-d|-g] but -p will take precedence)
      Use the following optimized preseed but modify its settings to your environment: 
        $PRESURL 
-  -d directory (preseed.cfg must exist in dir root)
-  -g github repo (must be github hosted)
+  -d skeleton directory (preseed.cfg must exist in dir root)
+  -g github repo skeleton directory (must be github hosted)
   -a architecture [i386|amd64]
-  -r release_codename (lsb_release -c)
+  -r release_codename (oneiric, natty, maveric, etc)
+  -cg chef repo (a github url)
+  -dg chef repo directory
   -o <file> Write output to <file> instead of custom.iso
   -k keep tmp dir
 
@@ -33,6 +35,10 @@ else
           REL=$1;;
       -o) shift
           ISO=$1;;
+      -cg) shift
+           CHEFGITH=$1;;
+      -cd) shift
+           CHEFCDIR=$1;;
       -k) KEEP=1;;
       -t) TEST=1;;
       *) echo "$USAGE" && exit 1;;
@@ -136,6 +142,12 @@ if [ $GITH ]; then
   fi
 fi
 
+if [ $CHEFCDIR ]; then
+  if [ ! -d $CHEFCDIR ]; then
+    echo "$CHEFCDIR not a valid dir" && exit 1
+  fi
+fi
+
 ## MAKING THE ISO ##
 echo "Downloading linux files.."
 FURL="${RELURL}main/installer-${ARCH}/current/images/netboot/ubuntu-installer/$ARCH"
@@ -176,21 +188,23 @@ EOF
 
 cp $PRESEED "$INITRD/preseed.cfg"
 ROOTD="$INITRD/root_skel/root"
-CHEFS="$ROOTD/chef-solo/cookbooks/chef-server"
+SOLOD="$ROOTD/chef-solo"
+CHEFS="$SOLOD/cookbooks/chef-server"
 mkdir -p $CHEFS/files/default $CHEFS/recipes
+
 if [ $CDIR ] && [ -d $CDIR ]; then
   (cd $CDIR ; cp -arp * $INITRD/root_skel)
 fi
 
-if [ ! -f $ROOTD/chef-solo/solo.rb ]; then
-  cat>$ROOTD/chef-solo/solo.rb<<EOF
+if [ ! -f $SOLOD/solo.rb ]; then
+  cat>$SOLOD/solo.rb<<EOF
 file_cache_path "/root/chef-solo"
 cookbook_path "/root/chef-solo/cookbooks"
 EOF
 fi
 
-if [ ! -f $ROOTD/chef-solo/solo.json ]; then
-  cat>$ROOTD/chef-solo/solo.json<<EOF
+if [ ! -f $SOLOD/solo.json ]; then
+  cat>$SOLOD/solo.json<<EOF
 {
   "run_list": [ "recipe[chef-server::default]" ]
 }
@@ -222,9 +236,28 @@ apt-get update
 CFDIR="/root/chef-solo"
 update-grub
 chef-solo -c \$CFDIR/solo.rb -j \$CFDIR/solo.json
-sed -i 's,sh /root/first_run.sh,su root -c "ruby /home/ubuntu/knife_first_run.rb",' /etc/rc.local
+sed -i 's,sh /root/first_run.sh,sh /root/second_run.sh,' /etc/rc.local
 sed -i '/^\*.*$/d' /etc/issue
 reboot
+EOF
+fi
+
+SECRUN="$ROOTD/second_run.sh"
+if [ ! -f $SECRUN ]; then
+  cat>$SECRUN<<EOF
+#!/bin/sh
+ETC='/etc/chef'
+HOMEC='/home/ubuntu/.chef'
+mkdir \$HOMEC
+cp \$ETC/webui.pem \$HOMEC
+cp \$ETC/validation.pem \$HOMEC
+chown -R ubuntu \$HOMEC
+su ubuntu -c "ruby /home/ubuntu/knife_first_run.rb"
+CHEFREPO="/home/ubuntu/chef-repo"
+chown -R ubuntu \$CHEFREPO
+( cd \$CHEFREPO ; su ubuntu -c "knife cookbook upload --all" )
+chef-client
+sed -i 's,sh /root/second_run.sh,exit 0,' /etc/rc.local;
 EOF
 fi
 
@@ -240,13 +273,8 @@ if [ ! -f $KFRUN ]; then
 require 'chef/knife'
 require 'ftools'
 homed='/home/ubuntu'
-confd='/etc/chef'
 homechf="#{homed}/.chef"
 repod="#{homed}/chef-repo"
-Dir.mkdir(homechf) unless File.directory?(homechf)
-Dir.mkdir(repod) unless File.directory?(repod)
-File.cp("#{confd}/webui.pem", homechf)
-File.cp("#{confd}/validation.pem", homechf)
 subcommand_loader = Chef::Knife::SubcommandLoader.new(false)
 commands_loaded = subcommand_loader.load_commands
 knifeconf = Chef::Knife::Configure
@@ -261,11 +289,6 @@ instance.config[:validation_client_name]='chef-validator'
 instance.config[:validation_key]="#{homechf}/validation.pem"
 instance.config[:repository]="#{repod}"
 instance.run_with_pretty_exceptions
-RCF='/etc/rc.local'
-str='su ubuntu -c "ruby /home/ubuntu/knife_first_run.rb"'
-rcfcontent=File.read RCF
-rcfcontent.gsub!(/#{str}/, '')
-File.open(RCF, 'w') {|f| f.write rcfcontent}
 EOF
 fi
 
@@ -283,6 +306,31 @@ echo '* INSTALL NOT COMPLETE - WILL REBOOT MOMENTARILY *' >> /etc/issue
 echo '**************************************************' >> /etc/issue
 sed -i 's,exit 0,sh /root/first_run.sh,' /etc/rc.local;
 EOF
+fi
+
+REPOERR="invalid chef repo (no cookbooks)"
+CHEFREPO="$USER_HOME/chef-repo"
+if [ $CHEFCDIR ]; then
+  if [ ! -d $CHEFCDIR/cookbooks ]; then
+    echo "$CHEFCDIR $REPOERR" && exit 1
+  fi
+  cp -arp $CHEFCDIR $CHEFREPO
+fi
+if [ $CHEFGITH ]; then
+  CHEFGITN=`expr $CHEFGITH : '.*github.com/\(.*\).git'`
+  if [ ! $CHEFGITN ]; then
+    echo "$CHEFGITH invalid github repo url" && exit 1
+  fi
+  echo "Exporting chef github repo..."
+  OUTPUT=`(cd $TMPDIR; curl -kLs https://github.com/$CHEFGITN/tarball/master|tar -zxv)`
+  CHEFGITDIR="$TMPDIR/`echo $OUTPUT|awk '{print $1}'`"
+  if [ ! $CHEFGITDIR ]; then
+    echo "Unable to download repo tarball" && exit 1
+  fi
+  if [ ! -d $CHEFGITDIR/cookbooks ]; then
+    echo "$CHEFGITDIR $REPOERR" && exit 1
+  fi
+  mv $CHEFGITDIR $CHEFREPO
 fi
 
 echo "Making the ISO..."
