some fixes caught while testing

diff --git a/stackjump b/stackjump
--- a/stackjump
+++ b/stackjump
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 SKELURL="http://github.com/jhtran/stackjump_skeleton"
-DISTURL=" http://us.archive.ubuntu.com/ubuntu/dists"
+DISTURL="http://us.archive.ubuntu.com/ubuntu/dists"
 USAGE="$0 options
   -p preseed (or use [-d|-g] but -p will take precedence)
   -d directory (preseed.cfg must exist in dir root)
@@ -32,6 +32,7 @@ else
           ISO=$1;;
       -k) KEEP=1;;
       -t) TEST=1;;
+      *) echo "$USAGE" && exit 1;;
     esac
     shift
   done
@@ -59,7 +60,7 @@ if [ $PFILE ]; then
     echo "$PFILE not a valid preseed file" && exit 1
   else
     PRESEED=$PFILE
-    SEED_WARN="Warning: $CDIR contains a preseed.cfg but -p $PRESEED takes precedence"
+    SEED_WARN="contains a preseed.cfg but -p $PRESEED takes precedence"
   fi
 fi
 
@@ -68,7 +69,7 @@ if [ $CDIR ]; then
     echo "Directory $CDIR invalid" && exit 1
   else
     if [ $PFILE ]; then 
-      echo "$SEED_WARN"
+      echo "Warning: $CDIR $SEED_WARN"
     else
       PRESEED="$CDIR/preseed.cfg"
       if [ ! -f $PRESEED ]; then
@@ -100,13 +101,14 @@ RELURL="$DISTURL/$REL/"
 HEAD=`curl -s --head $RELURL|head -1`
 HCODE=`expr "$HEAD" : 'HTTP\/... \(...\) '`
 if [ "$HCODE" != '200' ]; then
-  echo "Release $REL invalid" && exit 0
+  echo "Release $REL invalid."
+  echo "Check $DISTURL to make sure a valid release codename" && exit 0
 fi
 
 if [ $GITH ]; then
   GITNAME=`expr $GITH : 'git@github.com:\(.*\).git'`
   if [ ! $GITNAME ]; then
-    echo "$GITH invalid github repo.  (Should be git@github.com:username/reponame)" && exit 1
+    echo "$GITH invalid github repo.  (Should be git@github.com:username/repo.git)" && exit 1
   fi
   echo "Exporting github repo..."
   OUTPUT=`(cd $TMPDIR ; curl -kLs https://github.com/$GITNAME/tarball/master|tar -zxv)`
@@ -116,7 +118,7 @@ if [ $GITH ]; then
   fi
   CDIR=$GITDIR
   if [ $PFILE ]; then
-    echo "$SEED_WARN"
+    echo "Warning: $GITH $SEED_WARN"
   else
     PRESEED="$GITDIR/preseed.cfg"
     if [ ! -f $PRESEED ]; then
